on: [ push ]
jobs:
  src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.11.2
          vessel-version: 0.6.3
      - run: for i in test/*.mo ; do $(vessel bin)/moc $(vessel sources 2>/dev/null) -r $i ; done
      - run: pushd example; $(vessel bin)/moc -r $(vessel sources 2>/dev/null) example.mo; popd
